services:
  app:
    build: .
    container_name: rastros_musical_app
    volumes:
      - .:/app
      - ./data:/app/data
    ports:
      - "8000:8000"
    environment:
      - ENV=development
      - DATABASE_PATH=/app/data/processed/rastros.duckdb
      - PYTHONPATH=/app
    stdin_open: true
    tty: true


  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: rastros_musical_web
    ports:
      - "5173:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - app
    environment:
      - VITE_API_URL=http://localhost:8000
    stdin_open: true
    tty: true

volumes:
  duckdb_data: